### ISSUE TITLE
Edit task fields

### ISSUE THREAD

**Issue by lucasdutraf** [lucasdutraf/Scheduler#11]
### Description
The user should have access to editable fields for editing tasks

### Tasks
* [ ]  Title - required - text field
* [ ]  Description - text field
* [ ]  Completed - check box
* [ ]  Deadline - MM/DD/YYYY format
