### ISSUE TITLE
Update task dialog box 

### ISSUE THREAD

**Issue by lucasdutraf** [lucasdutraf/Scheduler#14]
### Description

After the user clicks the update button, a dialog box must pop up with a yes no button

### Tasks
* [ ] Implement dialog box
* [ ] Yes action - POST method
* [ ] No action - close dialog
