### ISSUE TITLE
Delete task dialog box

### ISSUE THREAD

**Issue by lucasdutraf** [lucasdutraf/Scheduler#15]
### Description

After the user clicks the delete button, a dialog box must pop up with a yes no button

### Tasks
* [ ] Implement dialog box
* [ ] Yes action - POST method
* [ ] No action - close dialog
