### ISSUE TITLE
"Create new" button

### ISSUE THREAD

**Issue by lucasdutraf** [lucasdutraf/Scheduler#5]
### Description

At main screen a button should redirect user no new task page.

### Tasks

- [x] Implement the button
- [ ] Connect button to new task page
- [ ] Make button clickable
