### ISSUE TITLE
Required fields

### ISSUE THREAD

**Issue by lucasdutraf** [lucasdutraf/Scheduler#6]
### Description
The user should have access to editable fields for creating new tasks

### Tasks
- [ ] Title - required - text field
- [ ] Description - text field
- [ ] Completed - check box
- [ ] Deadline - MM/DD/YYYY format
