### ISSUE TITLE
Task created dialog box 

### ISSUE THREAD

**Issue by lucasdutraf** [lucasdutraf/Scheduler#8]
### Description

After the success of create a task request, a dialog box must pop up and after click "OK" button redirect user to the Main Screen

### Tasks
- [ ] Implement dialog box
- [ ] Make the "OK" button clickable
- [ ] Redirect the user to Main Screen
